### ISSUE TITLE
为啥这ip更新的这么频繁啊，频繁改有点难受。

### ISSUE THREAD

**Issue by coderbruis** [ineo6/hosts#1]

**Comment by ineo6** [comment]
目前无法得知ip有效性，所以是从最新ip中获取一个，后续可能的话会优化下更新。

目前你通过SwitchHost自动更新会好点。

**Comment by coderbruis** [comment]
> 目前无法得知ip有效性，所以是从最新ip中获取一个，后续可能的话会优化下更新。
> 
> 目前你通过SwitchHost自动更新会好点。

SwitchHost windows报无法修改hosts，我用管理员身份启动了SwitchHost都不好使，咋用的啊。另外SwtichHost必须启动在后台挂着，才能实时更新Hosts吗？

**Comment by ineo6** [comment]
可以参考 https://github.com/oldj/SwitchHosts/issues/513

另外确实是要在后台挂着，只有运行才会执行同步。
