### ISSUE TITLE
方案缺陷

### ISSUE THREAD

**Issue by xljiulang** [ineo6/hosts#11]
此方案解决了dns污染问题，但不能解决github  tcp rst的本质问题。

**Comment by ineo6** [comment]
项目的定位就是简单解决部分问题，复杂方案不需要考虑连接重置问题。

**Comment by xljiulang** [comment]
很多省市的网络下，直接用不了。。

**Comment by ineo6** [comment]
最有效的方式当然是架个梯子，`host`方案本来就不能抗干扰，不是所有网络情况下都能很好的使用。

**Comment by anjia0532** [comment]
是否可以考虑部分域名加一下 https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses ？官方 ip address cidr 测速（只开放了部分域名）
