### ISSUE TITLE
我写了一个py小脚本，配置此教程可以一键更新host和dns

### ISSUE THREAD

**Issue by john0618** [ineo6/hosts#13]
`import requests
import os

# 此脚本需要将hosts.txt的文件文件操作权限（修改、写入）赋予给当前user，不然会显示拒绝访问！

'''
国内镜像地址：https://gitee.com/ineo6/hosts
主站地址为：https://github.com/ineo6/hosts
'''

url = "https://gitee.com/ineo6/hosts/raw/master/hosts"  # hosts源码

r = requests.get(url=url)

hosts = r.text

with open('C:\\Windows\\System32\\drivers\\etc\\hosts.txt', 'w+') as f:
	f.write(hosts)

os.system("ipconfig /flushdns")

print("hosts文件更新完毕，DNS缓存刷新完毕！")
`

**实现效果如图**

![微信图片_20220219131318](https://user-images.githubusercontent.com/32479167/154787247-0b0363ae-f189-4b16-b654-c8e4678d13ac.png)

有办法可以让他每次开机就运行吗？（windows系统）

**Comment by volksvagen** [comment]
@john0618 用Windows的task scheduler添加开机启动项。

**Comment by john0618** [comment]
Ohhh!! I got it. Thanks
