### ISSUE TITLE
gitee 的 host 挂了

### ISSUE THREAD

**Issue by JinPengGeng** [ineo6/hosts#18]
https://gitee.com/ineo6/hosts/raw/master/hosts

你的访问受限！
服务器拒绝处理您的请求！您可能没有访问此操作的权限，[点击这里](https://gitee.com/)返回首页

**Comment by ineo6** [comment]
已更换到`Gitlab`。

https://gitlab.com/ineo6/hosts

- https://gitlab.com/ineo6/hosts/-/raw/master/hosts
- https://gitlab.com/ineo6/hosts/-/raw/master/next-hosts
