### ISSUE TITLE
[BUG]域名解析错误

### ISSUE THREAD

**Issue by Rexexe** [ineo6/hosts#2]
下图中的判断应该是大于2，不然所有域名都为真，但是github.com这种只有主域名的地址会出现404造成报错

![image](https://user-images.githubusercontent.com/27289798/118074043-c63e9080-b3df-11eb-86b3-57ba3ea85e90.png)

结果就是host文件里面所有主域名的ip都没有
github.io
github.com
githubstatus.com
github.community

另外

![image](https://user-images.githubusercontent.com/27289798/118074286-3220f900-b3e0-11eb-81ce-fe422eab9e8b.png)

建议增加类型判断或者正则判断ip

![image](https://user-images.githubusercontent.com/27289798/118074439-7b714880-b3e0-11eb-894b-a3e9f3177b06.png)

因为可能会有CNAME、TXT等类型解析

**Comment by ineo6** [comment]
感谢，如果动手能力强的话可以直接给个`PR`😁
