### ISSUE TITLE
你好  

### ISSUE THREAD

**Issue by xingleiwu** [ineo6/hosts#22]
就像这种本地获取hosts 链接     http://localhost:8888  有办法直接下载成hosts文件吗  我想用树莓派 直接下载 然后替换hosts文件 
就像这种命令
0 */3 * * * cd /etc/storage/dnsmasq;rm -rf hosts;wget --no-check-certificate https://gitlab.com/ineo6/hosts/-/raw/master/hosts -O hosts;restart_dhcpd
本地链接这个 怎么设置 可以直接下载hosts文件
本地链接下载的 如图是 上面那种网页格式的
你的网络链接下载的是hosts文件格式
本地链接能直接下载下面那种格式吗
![image](https://user-images.githubusercontent.com/13015600/182286407-57e1e4cd-cf2f-4ff0-bf35-bdc970522f14.png)

**Comment by claviering** [comment]
你把 hosts 文件放在本地服务器到public目录试试

**Comment by claviering** [comment]
你的hosts文件是放在 服务器 http://localhost:8888/ 的什么地方？你服务器的配置不对，请求http://localhost:8888/，肯定是返回index.html，你要请求 http://localhost:8888/[your hosts path]

**Comment by ineo6** [comment]
可以把那个html挂个链接让我看下。

本地和服务器上的地址本质没什么太大区别，我用mac测试返回的都是正常的。
