### ISSUE TITLE
求Pixiv Host

### ISSUE THREAD

**Issue by wintopic** [ineo6/hosts#33]
https://www.pixiv.net/
也可以用同样的方式直连，求大大更新

**Comment by ineo6** [comment]
据我所知并不行，Pixiv能用的ip是没法自动获取到。

或者你有稳定的获取方式可以提供出来。

**Comment by 2584191127** [comment]
> 据我所知并不行，Pixiv能用的ip是没法自动获取到。
> 
> 或者你有稳定的获取方式可以提供出来。

大佬，请问怎么要知道一个网站能不能通过改hosts来访问？
