### ISSUE TITLE
How can you get these IP address? 你如何能得到这些IP地址？

### ISSUE THREAD

**Issue by samho2008** [ineo6/hosts#34]
How can you get these IP address? I mean, where you can get the original IP address for the GitHub hosts.
如何获得这些 IP 地址？我的意思是，你在哪里可以得到GitHub主机的原始IP地址。

**Comment by ineo6** [comment]
不是GitHub的原始地址，网站肯定用的CDN。获取方式是通过公开的域名查询IP工具。
