### ISSUE TITLE
改host的方法是不是将成为历史？

### ISSUE THREAD

**Issue by Olimiya** [ineo6/hosts#36]
![E_2 {MV4FV8TMB937X(N5E7](https://user-images.githubusercontent.com/35156329/205920905-bf7f60de-2dc6-4cbc-93af-416fb8d1ca41.jpg)
 
按照这个说法，图的说法没找到出处。

但是实测结果：https://ping.chinaz.com/github.com。

![image](https://user-images.githubusercontent.com/35156329/205921148-7f4e8c14-de01-459a-a02a-570985199616.png)

**Comment by ineo6** [comment]
肯定是瞎扯啊，这个测速网站的服务器并不是权威的。很早之前应该就是这样了。如果要搞GitHub的域名，为什么不直接封了。
