### ISSUE TITLE
无内容

### ISSUE THREAD

**Issue by HayBale** [ineo6/hosts#6]
没有ip
# GitHub Host Start

# Please Star : https://github.com/ineo6/hosts
# Mirror Repo : https://gitee.com/ineo6/hosts
# Update at: 2021-05-28 16:40:47

# GitHub Host End

**Comment by solszl** [comment]
fetch添加headers 即可解决

**Comment by HayBale** [comment]
两天没更新了，不会出事吧

**Comment by solszl** [comment]
> 两天没更新了，不会出事吧

获取ip网站禁止 没有UA 请求。 现在请求403， 添加UA 再运行程序即可。

**Comment by ineo6** [comment]
已确认，我处理下请求头。

**Comment by ineo6** [comment]
Fixed.
