### ISSUE TITLE
SwitchHosts 自动更新与手动更新的地址延时较大

### ISSUE THREAD

**Issue by lfl-0** [ineo6/hosts#7]
你好，感谢贡献，问题如题。
手动：
![image](https://user-images.githubusercontent.com/48972687/123896823-e37ded00-d994-11eb-981e-0bf3e6193494.png)
自动：
![image](https://user-images.githubusercontent.com/48972687/123896937-1aec9980-d995-11eb-88f0-4f46038b11b9.png)

**Comment by ineo6** [comment]
没有看懂，意思是自动更新不够及时，没有获取最新的IP?

**Comment by lfl-0** [comment]
SwitchHosts 地址：https://cdn.jsdelivr.net/gh/ineo6/hosts/hosts
对，就是上面这个地址获取的 hosts 不是最新的

**Comment by ineo6** [comment]
懂了，是CDN缓存的问题。

源地址是：https://raw.githubusercontent.com/ineo6/hosts/master/hosts
但是因为网络问题，很可能无法访问。

这是一个先有鸡还是先有蛋的问题了。

**Comment by lfl-0** [comment]
可以把这个地址加到 Readme 中，Gitee 访问没问题
Gitee 源地址：https://gitee.com/ineo6/hosts/raw/master/hosts

**Comment by ineo6** [comment]
Done.
