### ISSUE TITLE
自动更新与现实还是有差距

### ISSUE THREAD

**Issue by zuorong-zhang-contributer** [ineo6/hosts#8]
![](https://raw.githubusercontent.com/zuorong-zhang-contributer/images/main/%E6%8D%95%E8%8E%B7.PNG)
![](https://github.com/zuorong-zhang-contributer/images/raw/main/%E6%8D%95%E8%8E%B71.PNG)

**Comment by zuorong-zhang-contributer** [comment]
我建议还是从一个dns查询网站爬IP，例如ipaddress

**Comment by ineo6** [comment]
使用的`hosts`文件地址是哪个？

**Comment by ineo6** [comment]
在十点十分是更新了，https://github.com/ineo6/hosts/commit/938b02d0bf10ecb44430779496484b589e458cee

目前`Action`是两小时更新一次，另外内部就是使用的`ipaddress`。

会再考虑设置什么频率会比较好。
