### ISSUE TITLE
gitee镜像地址不会出现违规吗？

### ISSUE THREAD

**Issue by JohyC** [ineo6/hosts#9]
我也写了个脚本解析hosts。但是镜像到gitee总是报违规，导致每次都不能准确同步hosts。
我之前写的其他脚本在gitee上也经常违规！
想问一下作者如何解决gitee违规问题！

**Comment by ineo6** [comment]
具体是用什么方式同步的？我这边的同步记录里偶尔也有一些失败的。

**Comment by JohyC** [comment]
> 具体是用什么方式同步的？我这边的同步记录里偶尔也有一些失败的。

我用的 Yikun/hub-mirror-action@master action库同步的。每次同步成功了，但是gitee显示违规，必须要自己手动申诉一下。
具体代码路径： 
- https://github.com/JohyC/Hosts/blob/main/.github/workflows/GithubHosts.yml

**Comment by ineo6** [comment]
我也用过`Yikun/hub-mirror-action`，不过也没发现问题。

怀疑可能是调用频率太高，·`Yikun/hub-mirror-action`内部实现还使用了`api`，建议你是换成单仓库同步`Action`试下。

**Comment by JohyC** [comment]
> 我也用过`Yikun/hub-mirror-action`，不过也没发现问题。
> 
> 怀疑可能是调用频率太高，·`Yikun/hub-mirror-action`内部实现还使用了`api`，建议你是换成单仓库同步`Action`试下。

可以的！下次试试。我给你提了个PR，你可以看一下。可以清除早就没用过时的workflows。
